name: Cache rustc
description: Caches rustc output with sccache
runs:
  using: "composite"
  steps:
    - name: Install sccache
      shell: pwsh
      run: |
        choco install sccache
        echo "SCCACHE_DIR=C:\Users\runneradmin\.sccache" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "SCCACHE_CACHE_SIZE=2G" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "RUSTC_WRAPPER=sccache" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - name: Save sccache
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.sccache
        key: ${{ runner.os }}-sccache-v2-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-sccache-v2-
    - name: Start sccache server
      shell: pwsh
      run: sccache --start-server
