name: Cache rust
description: Caches rustc using sscache and cargo data
inputs:
  cargo:
    description: Cache cargo
    required: true
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-cargo-
