[package]
name = "mqpkg-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mqpkg"
path = "src/main.rs"

[dependencies]
mqpkg = { path = "../mqpkg" }
anyhow = "1.0"
camino = "1.0.7"
clap = { version = "3.1.0", features = ["derive"] }
dunce = "1.0.2"
vfs = "0.5.2"
