name: Bloat


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  bloat:
    name: Bloat
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: --release --locked
          tree_args: --locked
