name: Security


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  audit:
    name: Audit
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
